name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USER_NAME_DOCKER }}
        password: ${{ secrets.USER_DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t saros2/hello-world:latest .
      
    - name: Push Docker image
      run: docker push saros2/hello-world:latest

